### ISSUE TITLE
Getting error while running Getting FileID cell

### ISSUE THREAD

**Issue by zerorail** [S-Nuttapong/Detecing-OnepuncmanHeroes#2]
i am trying to run this cell but i am getting this error 

`W0718 15:34:13.979573 139889619875712 __init__.py:44] file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth

/content/Gdrive/My Drive/Tensorflow
/content/Gdrive/My Drive/Tensorflow/workspace
/content/Gdrive/My Drive/Tensorflow/workspace/training_OPM1
Extracted zip file 1QnZAojST0lQnQSPuoeIxZN9_LMAl4EkR.zip
`

**Comment by zerorail** [comment]
i fixed that error by adding this in the code

import logging
logging.getLogger('googleapiclient.discovery_cache').setLevel(logging.ERROR)
